### ISSUE TITLE
Contains constrain

### ISSUE THREAD

**Issue by reflexdemon** [thenativeweb/assertthat#13]
Hey,

I was trying to look for some type of assertion tool and found that `assertthat` is close to what I need.
Is there a feature that I can request?

It would be good if these assertions can be added to make it really useful for the developers.

* contains(containing)
```javascript
assert.that(actual).is.containing(expected);
assert.that(actual).is.not.containing(expected);
```

[The API that was inspired of for this issue](http://stringjs.com/#methods/contains-ss)

*  endsWith
```javascript
assert.that(actual).is.endsWith(expected);
assert.that(actual).is.not.endsWith(expected);
```

[The API that was inspired of for this issue](http://stringjs.com/#methods/endswith-ss)

*  startsWith
```javascript
assert.that(actual).is.startsWith(expected);
assert.that(actual).is.not.startsWith(expected);
```
[The API that was inspired of for this issue](http://stringjs.com/#methods/startswith-prefix)

**Comment by goloroden** [comment]
I think, these are good ideas, and I will implement them.

Give me a few days… :-)
