### ISSUE TITLE
Want matching() method

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/assertthat#16]
I wish I could use assert.that(actual).is.matching(expectedRegexp);

right now, a regular expression is only supported in assert.that(f).is.throwing(expected);

working around using startingWith(), endingWith() and containing() is a pain.

**Comment by goloroden** [comment]
Thanks for the idea, I like it :-)

I will implement this, I just do not yet know when (the next days are quite busy). Would you mind sending a PR?

**Comment by stefanheine** [comment]
thanks!
it would be great if you could update the documentation to say:
Asserts that _actual_ matches _expected_ **regular expression**.

that way it would be easier to find that function if you're searching for 'regular expression' on the page.

**Comment by goloroden** [comment]
Fixed in https://github.com/thenativeweb/assertthat/commit/7223a7c8cfafaa6c7136c96a7625074e31bdb9e0
