### ISSUE TITLE
"Reflect is not defined" error when assertion failed (Node v4.3.2)

### ISSUE THREAD

**Issue by halimath** [thenativeweb/assertthat#21]
When using `assertthat` >= 0.7.* on my project I ran into the following error whenever an assertion fails. I can reproduce this error using the following "shell session" running in an empty directory:

```
$ npm install assertthat
assertthat@0.8.1 node_modules/assertthat
├── comparejs@0.1.5
└── stringify-object@2.4.0 (is-regexp@1.0.0, is-plain-obj@1.1.0)

$ node -e '(require("assertthat")).that("a").is.equalTo("b")'
/tmp/assertthat-bug/node_modules/assertthat/lib/fail.js:20
  assert.fail(undefined, undefined, Reflect.apply(util.format, this, newArgs));
                                    ^

ReferenceError: Reflect is not defined
    at values (/tmp/assertthat-bug/node_modules/assertthat/lib/fail.js:20:37)
    at Object.equalTo (/tmp/assertthat-bug/node_modules/assertthat/lib/constraints/equalTo.js:17:5)
    at [eval]:1:38
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:574:27
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
```

The same error also occurs when using `assertthat@0.7.2`.

When using `assertthat@0.6.0` I get the following output:

```
$ node -e '(require("assertthat")).that("a").is.equalTo("b")'

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Expected 'a' to equal 'b'.
    at fail (/tmp/assertthat-bug/node_modules/assertthat/lib/fail.js:24:10)
    at Object.equalTo (/tmp/assertthat-bug/node_modules/assertthat/lib/constraints/equalTo.js:17:5)
    at [eval]:1:38
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:574:27
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
```

I am using node v4.3.2 on OS X 10.11.

**Comment by goloroden** [comment]
Thanks for bringing up this issue.

`Reflect` is an API that is not available in Node.js 4 (and so far, we weren't concerned about Node.js 4 support any more, since Node.js 6 is the new LTS).

Is updating Node.js an option for you?

**Comment by halimath** [comment]
Thanks for the fast response.

Unfortunately, upgrading to node 6 is not an option. We decided to switch to node 4 (which was the LTS release at that time) for production and currently have no plans (and time) to do another major upgrade.

Do you know of any polyfill drop in replacement for `Reflect`? Otherwise, I think we can go with the 0.6.x release for our tests.

Maybe you can add an [engine](https://docs.npmjs.com/files/package.json#engines) key to the `package.json` to describe the required node version?

**Comment by goloroden** [comment]
Actually, there is a polyfill that I was able to use, [harmony-reflect](https://github.com/tvcutsem/harmony-reflect).

Using this polyfill it works on Node.js 6.x, Node.js 7.1, and on the version used by you - Node.js 4.3.2.

I will publish a new version within the next minutes :-)

**Comment by goloroden** [comment]
Version 0.8.2 (which contains the fix) is released :-)

**Comment by halimath** [comment]
Thanks a lot.
