### ISSUE TITLE
Out of memory error when asserting with react fibers

### ISSUE THREAD

**Issue by yeldiRium** [thenativeweb/assertthat#256]
We have a project where we use assertthat to test react components. We use [@testing-library](https://testing-library.com/docs/react-testing-library/intro/) for this.

One tests case roughly looks like this:

```typescript
import { assert } from 'assertthat';
import { render } from '@testing-library/react';

test('foo', async (): Promise<void> => {
  const { queryByText } = render(
    <SomeComponent />
  );

  const nodeThatShouldNotExist = queryByText('foo');

  assert.that(nodeThatShouldNotExist).is.null();
});
```

The call to `queryByText('foo')` here returns an `HTMLElement` (because the test is wrong). So the assumption is that the assertion will fail. Instead it does not complete and the process runs out of memory.

The problem is probably not with `assertthat`, but with `comparejs`, but I did not have the time to debug this far enough to see where the problem arises.

My first suspicion was that this was due to bad handling of circular references, but that does not seem to be the case. My best bet is that the `unbox` method in `comparejs` is somehow broken with html elements.

**Comment by strangedev** [comment]
In said project, after upgrading to the new version of this library, we do not see this error anymore. We do, however, have another error for which I created another issue (#346).

I will close this now, as the method in question does not exhibit the error anymore.
