### ISSUE TITLE
Cannot find module 'assertthat'

### ISSUE THREAD

**Issue by seal-mbo** [thenativeweb/assertthat#32]
Since switching to typescript (version 4.0.0), the "main"-file cannot be found anymore.

Solution: Do not link the main file to `lib/assertThat.js`, but instead to `build/lib/assertThat.js`.

See: https://github.com/thenativeweb/assertthat/pull/31

**Comment by yeldiRium** [comment]
Thank you for your contribution. The issues are resolved in v4.0.1, which was just released.
