### ISSUE TITLE
"Unexpected token {" in is-subset-of@2.0.0

### ISSUE THREAD

**Issue by seal-mbo** [thenativeweb/assertthat#33]
I encountered another issue in the dependencies of the new `4.0.x`-release; it appears that in `is-subset-of`, in version `2.0.0`, there is a syntax error:

```
[...]/node_modules/assertthat/node_modules/is-subset-of/build/lib/isSubsetOf.js:38
                        catch {
                              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([...]/node_modules/assertthat/node_modules/comparejs/build/lib/compare.js:6:40)
```

Would it be possible to downgrade the dependency to its previous version (we've got `1.0.0` running without a problem, for example)?
Am I the only one experiencing these issues? 🤔 It is a bit strange to receive such obvious errors after a version upgrade, as I expect that changes were tested before merging.

**Comment by goloroden** [comment]
Thanks for bringing this up 😊 

This is a so-called [optional catch binding](https://node.green/#ES2019-misc-optional-catch-binding), which was introduced in Node.js 10.3. Since we always only address latest LTS of Node.js, this probably means that you are using an elder version of Node.js, do you?

**Comment by seal-mbo** [comment]
Ah, yes, that will be it. We are currently still running on Node.JS `8.x`, and are right now on the way to update all modules.
In that case, we will temporarily stick to the `3.3.0`-release, and update after we have successfully introduced Node.JS 10.

**Comment by goloroden** [comment]
PS: Node.js 12 LTS will be out in October, so if you are now upgrading to 10, it may make more sense to directly go to 12 LTS in October – otherwise you will have to update again soon.
